version: '3'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: quienesquien
      POSTGRES_PASSWORD: manager

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/quienEsquien_App
    ports:
      - '8000:8000'
    depends_on:
      - db
