# Generated by Django 4.0.3 on 2022-03-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quienEsQuien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
